spring:
  application:
    name: server-consumer
server:
  port: 9090

eureka:
  client:
    service-url:
      #defaultZone 这个是不会提示的，此处需要自己写
      #实际上属性应该是service-url,这个属性是个map（key-value）格式；当key是defaultZone的时候才能被解析；所以这里没有提示，
      #但是自己还需要写一个defaultZone；
      defaultZone: http://peer3:9001/eureka,http://peer1:9002/eureka,http://peer2:9003/eureka


